//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberGuessingGui.NumberGuessService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NumberGuessService.INumberGuessing")]
    public interface INumberGuessing {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuessing/checkNumber", ReplyAction="http://tempuri.org/INumberGuessing/checkNumberResponse")]
        string checkNumber(int userNum, int SecretNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuessing/checkNumber", ReplyAction="http://tempuri.org/INumberGuessing/checkNumberResponse")]
        System.Threading.Tasks.Task<string> checkNumberAsync(int userNum, int SecretNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuessing/SecretNumber", ReplyAction="http://tempuri.org/INumberGuessing/SecretNumberResponse")]
        int SecretNumber(int lower, int upper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuessing/SecretNumber", ReplyAction="http://tempuri.org/INumberGuessing/SecretNumberResponse")]
        System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumberGuessingChannel : NumberGuessingGui.NumberGuessService.INumberGuessing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberGuessingClient : System.ServiceModel.ClientBase<NumberGuessingGui.NumberGuessService.INumberGuessing>, NumberGuessingGui.NumberGuessService.INumberGuessing {
        
        public NumberGuessingClient() {
        }
        
        public NumberGuessingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberGuessingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberGuessingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberGuessingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string checkNumber(int userNum, int SecretNum) {
            return base.Channel.checkNumber(userNum, SecretNum);
        }
        
        public System.Threading.Tasks.Task<string> checkNumberAsync(int userNum, int SecretNum) {
            return base.Channel.checkNumberAsync(userNum, SecretNum);
        }
        
        public int SecretNumber(int lower, int upper) {
            return base.Channel.SecretNumber(lower, upper);
        }
        
        public System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper) {
            return base.Channel.SecretNumberAsync(lower, upper);
        }
    }
}
