//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageClient.MsgService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MsgService.IMessagingService")]
    public interface IMessagingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/sendMessage", ReplyAction="http://tempuri.org/IMessagingService/sendMessageResponse")]
        void sendMessage(string senderID, string receiverID, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/sendMessage", ReplyAction="http://tempuri.org/IMessagingService/sendMessageResponse")]
        System.Threading.Tasks.Task sendMessageAsync(string senderID, string receiverID, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/receiveMessage", ReplyAction="http://tempuri.org/IMessagingService/receiveMessageResponse")]
        string[] receiveMessage(string receiverID, bool purge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/receiveMessage", ReplyAction="http://tempuri.org/IMessagingService/receiveMessageResponse")]
        System.Threading.Tasks.Task<string[]> receiveMessageAsync(string receiverID, bool purge);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessagingServiceChannel : MessageClient.MsgService.IMessagingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagingServiceClient : System.ServiceModel.ClientBase<MessageClient.MsgService.IMessagingService>, MessageClient.MsgService.IMessagingService {
        
        public MessagingServiceClient() {
        }
        
        public MessagingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void sendMessage(string senderID, string receiverID, string message) {
            base.Channel.sendMessage(senderID, receiverID, message);
        }
        
        public System.Threading.Tasks.Task sendMessageAsync(string senderID, string receiverID, string message) {
            return base.Channel.sendMessageAsync(senderID, receiverID, message);
        }
        
        public string[] receiveMessage(string receiverID, bool purge) {
            return base.Channel.receiveMessage(receiverID, purge);
        }
        
        public System.Threading.Tasks.Task<string[]> receiveMessageAsync(string receiverID, bool purge) {
            return base.Channel.receiveMessageAsync(receiverID, purge);
        }
    }
}
