//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SelfHostedNumberGuessingClient
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ISelfHostedNumberGuessing")]
    public interface ISelfHostedNumberGuessing
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISelfHostedNumberGuessing/SecretNumber", ReplyAction = "http://tempuri.org/ISelfHostedNumberGuessing/SecretNumberResponse")]
        int SecretNumber(int lower, int upper);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISelfHostedNumberGuessing/SecretNumber", ReplyAction = "http://tempuri.org/ISelfHostedNumberGuessing/SecretNumberResponse")]
        System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISelfHostedNumberGuessing/checkNumber", ReplyAction = "http://tempuri.org/ISelfHostedNumberGuessing/checkNumberResponse")]
        string checkNumber(int userNum, int SecretNum);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISelfHostedNumberGuessing/checkNumber", ReplyAction = "http://tempuri.org/ISelfHostedNumberGuessing/checkNumberResponse")]
        System.Threading.Tasks.Task<string> checkNumberAsync(int userNum, int SecretNum);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISelfHostedNumberGuessingChannel : ISelfHostedNumberGuessing, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelfHostedNumberGuessingClient : System.ServiceModel.ClientBase<ISelfHostedNumberGuessing>, ISelfHostedNumberGuessing
    {

        public SelfHostedNumberGuessingClient()
        {
        }

        public SelfHostedNumberGuessingClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public SelfHostedNumberGuessingClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SelfHostedNumberGuessingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public SelfHostedNumberGuessingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public int SecretNumber(int lower, int upper)
        {
            return base.Channel.SecretNumber(lower, upper);
        }

        public System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper)
        {
            return base.Channel.SecretNumberAsync(lower, upper);
        }

        public string checkNumber(int userNum, int SecretNum)
        {
            return base.Channel.checkNumber(userNum, SecretNum);
        }

        public System.Threading.Tasks.Task<string> checkNumberAsync(int userNum, int SecretNum)
        {
            return base.Channel.checkNumberAsync(userNum, SecretNum);
        }
    }
}
