//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowMessagingApplication.FileStoreService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileStoreService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PutStringToFile", ReplyAction="http://tempuri.org/IService/PutStringToFileResponse")]
        WorkflowMessagingApplication.FileStoreService.PutStringToFileResponse PutStringToFile(WorkflowMessagingApplication.FileStoreService.PutStringToFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PutStringToFile", ReplyAction="http://tempuri.org/IService/PutStringToFileResponse")]
        System.Threading.Tasks.Task<WorkflowMessagingApplication.FileStoreService.PutStringToFileResponse> PutStringToFileAsync(WorkflowMessagingApplication.FileStoreService.PutStringToFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStringFromFile", ReplyAction="http://tempuri.org/IService/GetStringFromFileResponse")]
        WorkflowMessagingApplication.FileStoreService.GetStringFromFileResponse GetStringFromFile(WorkflowMessagingApplication.FileStoreService.GetStringFromFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStringFromFile", ReplyAction="http://tempuri.org/IService/GetStringFromFileResponse")]
        System.Threading.Tasks.Task<WorkflowMessagingApplication.FileStoreService.GetStringFromFileResponse> GetStringFromFileAsync(WorkflowMessagingApplication.FileStoreService.GetStringFromFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PutStringToFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PutStringToFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string value;
        
        public PutStringToFileRequest() {
        }
        
        public PutStringToFileRequest(string fileName, string value) {
            this.fileName = fileName;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PutStringToFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PutStringToFileResponse {
        
        public PutStringToFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStringFromFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStringFromFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fileName;
        
        public GetStringFromFileRequest() {
        }
        
        public GetStringFromFileRequest(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStringFromFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStringFromFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetStringFromFileResult;
        
        public GetStringFromFileResponse() {
        }
        
        public GetStringFromFileResponse(string GetStringFromFileResult) {
            this.GetStringFromFileResult = GetStringFromFileResult;
        }
    }
}
