//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowMessagingApplication.MessagingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessagingService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/sendMessage", ReplyAction="http://tempuri.org/IService/sendMessageResponse")]
        WorkflowMessagingApplication.MessagingService.sendMessageResponse sendMessage(WorkflowMessagingApplication.MessagingService.sendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/sendMessage", ReplyAction="http://tempuri.org/IService/sendMessageResponse")]
        System.Threading.Tasks.Task<WorkflowMessagingApplication.MessagingService.sendMessageResponse> sendMessageAsync(WorkflowMessagingApplication.MessagingService.sendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/sendMessages", ReplyAction="http://tempuri.org/IService/sendMessagesResponse")]
        WorkflowMessagingApplication.MessagingService.sendMessagesResponse sendMessages(WorkflowMessagingApplication.MessagingService.sendMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/sendMessages", ReplyAction="http://tempuri.org/IService/sendMessagesResponse")]
        System.Threading.Tasks.Task<WorkflowMessagingApplication.MessagingService.sendMessagesResponse> sendMessagesAsync(WorkflowMessagingApplication.MessagingService.sendMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/receiveMessage", ReplyAction="http://tempuri.org/IService/receiveMessageResponse")]
        WorkflowMessagingApplication.MessagingService.receiveMessageResponse receiveMessage(WorkflowMessagingApplication.MessagingService.receiveMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/receiveMessage", ReplyAction="http://tempuri.org/IService/receiveMessageResponse")]
        System.Threading.Tasks.Task<WorkflowMessagingApplication.MessagingService.receiveMessageResponse> receiveMessageAsync(WorkflowMessagingApplication.MessagingService.receiveMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string receiverID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Message;
        
        public sendMessageRequest() {
        }
        
        public sendMessageRequest(string receiverID, string Message) {
            this.receiverID = receiverID;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendMessageResponse {
        
        public sendMessageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessages", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string senderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string receiverID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public sendMessagesRequest() {
        }
        
        public sendMessagesRequest(string senderID, string receiverID, string Message) {
            this.senderID = senderID;
            this.receiverID = receiverID;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessagesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class sendMessagesResponse {
        
        public sendMessagesResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receiveMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class receiveMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string receiverID;
        
        public receiveMessageRequest() {
        }
        
        public receiveMessageRequest(string receiverID) {
            this.receiverID = receiverID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receiveMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class receiveMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] receiveMessageResult;
        
        public receiveMessageResponse() {
        }
        
        public receiveMessageResponse(string[] receiveMessageResult) {
            this.receiveMessageResult = receiveMessageResult;
        }
    }
}
